package researchstack.wearable.standalone.domain.exception

object AlreadyJoinedStudy : RuntimeException()
