package researchstack.domain.exception

object AlreadyJoinedStudy : RuntimeException()
